modLoader="javafml" #mandatory
loaderVersion="[42,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="timestamp_chat" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Timestamp Chat" #mandatory
logoFile="pack.png" #optional
authors="Abbie" #optional
description='''
Adds timestamps to chat.
'''
[[dependencies.timestamp_chat]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[42,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.timestamp_chat]]
modId="minecraft"
mandatory=true
versionRange="[1.19.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.timestamp_chat]]
modId="cloth_config"
mandatory=true
versionRange="[8,)"
ordering="NONE"
side="BOTH"
