name: Publish

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - uses: Kir-Antipov/mc-publish@v3.2
        name: publish fabric
        with:
          files: fabric/build/libs/*
          modrinth-id: 2lAPv09G
          modrinth-featured: false
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 373235
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Kir-Antipov/mc-publish@v3.2
        name: publish forge
        with:
          files: forge/build/libs/*
          modrinth-id: 2lAPv09G
          modrinth-featured: false
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 373235
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          github-token: ${{ secrets.GITHUB_TOKEN }}
