name: Publish

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew build
      - uses: Kir-Antipov/mc-publish@v3.3
        name: publish fabric
        with:
          files: fabric/build/libs/!(*-@(dev-shadow|sources|javadoc)).jar
          modrinth-id: 2lAPv09G
          modrinth-featured: false
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 373235
          curseforge-name: ""
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Kir-Antipov/mc-publish@v3.3
        name: publish neoforge
        with:
          files: neoforge/build/libs/!(*-@(dev-shadow|sources|javadoc)).jar
          modrinth-id: 2lAPv09G
          modrinth-featured: false
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 373235
          curseforge-name: ""
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          github-token: ${{ secrets.GITHUB_TOKEN }}
